export const authErrorMessages: Record<string, string> = {
  CredentialsSignin: 'Invalid credentials',
  AccessDenied: 'Access denied',
  AccountNotLinked: 'Account not linked',
  AdapterError: 'Authentication adapter failed',
  CallbackRouteError: 'Login callback failed',
  DuplicateConditionalUI: 'UI misconfiguration detected',
  EmailSignInError: 'Email login failed',
  ErrorPageLoop: 'Login error page loop',
  EventError: 'Login event failed',
  ExperimentalFeatureNotEnabled: 'Experimental feature not enabled',
  InvalidCallbackUrl: 'Invalid callback URL',
  InvalidCheck: 'Security check failed',
  InvalidEndpoints: 'OAuth provider misconfigured',
  InvalidProvider: 'Unsupported auth provider',
  JWTSessionError: 'JWT session failed',
  MissingAdapter: 'Database adapter not found',
  MissingAdapterMethods: 'Missing adapter methods',
  MissingAuthorize: 'Missing credentials auth method',
  MissingCSRF: 'Missing CSRF token',
  MissingSecret: 'Auth secret missing',
  MissingWebAuthnAutocomplete: 'WebAuthn UI misconfigured',
  OAuthAccountNotLinked: 'OAuth account not linked',
  OAuthCallbackError: 'OAuth callback error',
  OAuthProfileParseError: 'OAuth profile parsing failed',
  OAuthSignInError: 'OAuth login failed',
  SessionTokenError: 'Session token issue',
  SignOutError: 'Logout failed',
  UnknownAction: 'Unknown login action',
  UnsupportedStrategy: 'Unsupported login strategy',
  UntrustedHost: 'Untrusted host',
  Verification: 'Email verification failed',
  WebAuthnVerificationError: 'WebAuthn failed',
};
